### ISSUE TITLE
sudo privs breaking on Ubuntu 16.x

### ISSUE THREAD

**Issue by mlp6** [suyashkumar/provision#1]
It appears that https://github.com/suyashkumar/provision/blob/94eaa72f63bb561a6284d103dbadeb484e2376aa/provision.sh#L7 doesn't play nicely on Ubuntu 16.x systems.  This was encountered by Julia when she tried to run this on the OIT VMs.  Quick inspection yielded `$0` -> `bash`; not sure if the original logic was for that to yield `provision.sh`. ??  Commenting this line out and explicitly running with `sudo` worked just fine without creating a unrecoverable UID 0 error.

Also might want to remove the `sudo` command on line https://github.com/suyashkumar/provision/blob/94eaa72f63bb561a6284d103dbadeb484e2376aa/provision.sh#L20 since that is redundant if already running with root priv.

**Comment by suyashkumar** [comment]
Good catch...this script has not been updated in a while, I should've checked it for 14.04 systems (sorry!)

**Comment by mlp6** [comment]
I am not sure why a bash script should change how your original line would be interpreted b/w different versions of Ubuntu... ?!
